### ISSUE TITLE
Write Hardware Requirements

### ISSUE THREAD

**Issue by lmfrench** [DiSSCo/dissco.github.io#4]
Information about Hardware requirements needs to be written for the website. Initially we will want to include a general hardware requirements page, and a page for the ALICE set-up. 

Dependency: #1  This will set up the pages and consider the structure of website to enable additional pages to be added in future.

**Comment by llivermore** [comment]
I have added a section to the ALICE workflow - is this too detailed? 

For the general hardware were you thinking something similar to the first page in the [iDigBio Imaging Equipment Recommendations (2015)](https://www.idigbio.org/sites/default/files/workshop-presentations/small-herbarium2013/iDigBioImagingEquipmentRecommendations1_0.pdf)?

**Comment by lmfrench** [comment]
General hardware was added at your suggestion - so whatever you think is useful for people.

Re ALICE: I don't think it is too detailed, but are the specific cameras listed a requirement or could something else be used?

**Comment by lmfrench** [comment]
Complete - [Digitisation Station](https://dissco.github.io/Digitisation/SpecimenImageCapture/DigitisationStation.html) page now live (we will continue to add to this but the initial page is live)
