### ISSUE TITLE
Header in DiSSCo Knowledge Base means content is below the cut 

### ISSUE THREAD

**Issue by llivermore** [DiSSCo/dissco.github.io#57]
![image](https://user-images.githubusercontent.com/7243779/212085950-c0c91702-05a8-4a3b-a7fa-554440911c34.png)

**Comment by lmfrench** [comment]
Closing, this relates to knowledgebase rather than digitisation guides site (@llivermore you could reopen this on the [Knowledgebase github](https://github.com/DiSSCo/kb))
